'use client';

import {FormEvent, useEffect, useState} from 'react';
import {LockKeyhole, RefreshCw, ShieldAlert, ShieldCheck, UserPlus, Users} from 'lucide-react';
import {ApiError, api} from '@/lib/api';

type User = {id:string;email:string;display_name:string;role:'ADMIN'|'USER';is_active:boolean;created_at:string;last_login_at:string|null};
type Audit = {event_id:string;event_type:string;timestamp:string;resource:string;result:string;safe_metadata:Record<string,unknown>};

export function AdminConsole() {
  const [users, setUsers] = useState<User[]>([]); const [events, setEvents] = useState<Audit[]>([]); const [globalKill, setGlobalKill] = useState(false); const [email, setEmail] = useState(''); const [role, setRole] = useState<'USER'|'ADMIN'>('USER'); const [message, setMessage] = useState(''); const [denied, setDenied] = useState(false);
  const refresh = async () => { try { const [userData, auditData, securityData] = await Promise.all([api<{users:User[]}>('/admin/users'), api<{events:Audit[]}>('/admin/audit'), api<{global_kill_switch:boolean}>('/admin/security')]); setUsers(userData.users); setEvents(auditData.events); setGlobalKill(securityData.global_kill_switch); setDenied(false); } catch (error) { if (error instanceof ApiError && error.status === 403) setDenied(true); else setMessage('Admin data could not be loaded.'); } };
  useEffect(() => { refresh(); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); try { await api('/admin/users/invite', {method:'POST', body:JSON.stringify({email, role})}); setEmail(''); setMessage('Invitation sent.'); refresh(); } catch { setMessage('Invitation could not be sent. Verify admin MFA and provider configuration.'); } }
  async function toggleKill() { try { const next = !globalKill; await api('/admin/security', {method:'PUT', body:JSON.stringify({global_kill_switch:next})}); setGlobalKill(next); setMessage(next ? 'Global trading kill switch is active.' : 'Global trading kill switch released.'); } catch { setMessage('Administrator MFA is required for this security control.'); } }
  async function updateUser(user: User, update: Record<string,unknown>) { try { await api(`/admin/users/${user.id}`, {method:'PATCH', body:JSON.stringify(update)}); refresh(); } catch { setMessage('The user update was not accepted.'); } }
  if (denied) return <div className="error-state"><LockKeyhole/><b>Administrator access required</b><span>This route is restricted to active administrator accounts with MFA verification.</span></div>;
  return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRATOR / SECURITY OPERATIONS</span><h1>Admin Console</h1><p>Invite-only access, audit visibility, global limits, and trading safety.</p></div><button className="btn" onClick={refresh}><RefreshCw/>Refresh</button></div><div className="admin-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">INVITE ONLY</span><h2>Users</h2></div><Users/></div><form className="admin-invite" onSubmit={invite}><input aria-label="Invite email" type="email" placeholder="name@example.com" value={email} onChange={event => setEmail(event.target.value)} required/><select aria-label="Invite role" value={role} onChange={event => setRole(event.target.value as 'USER'|'ADMIN')}><option value="USER">User</option><option value="ADMIN">Admin</option></select><button className="btn primary"><UserPlus/>Invite</button></form><div className="admin-users">{users.map(user => <div key={user.id}><span><b>{user.email}</b><small>{user.role} · {user.last_login_at ? `Last login ${new Date(user.last_login_at).toLocaleDateString()}` : 'Invitation pending'}</small></span><em className={user.is_active ? 'positive' : 'negative'}>{user.is_active ? 'ACTIVE' : 'DISABLED'}</em><button className="btn" onClick={() => updateUser(user, {is_active:!user.is_active})}>{user.is_active ? 'Deactivate' : 'Reactivate'}</button><button className="btn" onClick={() => updateUser(user, {role:user.role === 'ADMIN' ? 'USER' : 'ADMIN'})}>Make {user.role === 'ADMIN' ? 'User' : 'Admin'}</button></div>)}</div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">SYSTEM SAFETY</span><h2>Global Kill Switch</h2></div><ShieldAlert className={globalKill ? 'negative' : ''}/></div><p className="panel-note">Overrides every user trading action. Live trading remains permanently locked in this release.</p><button className={globalKill ? 'kill-switch armed' : 'kill-switch'} onClick={toggleKill}><ShieldCheck/>{globalKill ? 'GLOBAL KILL SWITCH ACTIVE' : 'Enable global kill switch'}</button></section><section className="panel wide"><div className="panel-head"><div><span className="eyebrow">IMMUTABLE-STYLE HISTORY</span><h2>Audit Log</h2></div></div><div className="audit-list">{events.map(event => <div key={event.event_id}><time>{new Date(event.timestamp).toLocaleString()}</time><b>{event.event_type}</b><span>{event.resource || 'System'}</span><em className={event.result === 'SUCCESS' ? 'positive' : 'negative'}>{event.result}</em></div>)}{!events.length && <p className="panel-note">No events are available yet.</p>}</div></section></div>{message && <div className="save-message">{message}</div>}</>;
}
