'use client';
import {ResponsiveContainer,AreaChart,Area,LineChart,Line,Tooltip,XAxis,YAxis} from 'recharts';
export function Panel({title,eyebrow,action,children,className=''}:{title?:string,eyebrow?:string,action?:React.ReactNode,children:React.ReactNode,className?:string}){return <section className={`panel ${className}`}>{(title||eyebrow)&&<header className="panel-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}{title&&<h2>{title}</h2>}</div>{action}</header>}{children}</section>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode,tone?:'good'|'bad'|'warn'|'neutral'}){return <span className={`badge ${tone}`}>{children}</span>}
export function Spark({data,positive=true,height=42}:{data:number[],positive?:boolean,height?:number}){return <div style={{height}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.map((v,i)=>({i,v}))}><defs><linearGradient id={positive?'up':'down'} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={positive?'#43d6ae':'#ff6685'} stopOpacity=".35"/><stop offset="1" stopColor={positive?'#43d6ae':'#ff6685'} stopOpacity="0"/></linearGradient></defs><Area dataKey="v" type="monotone" stroke={positive?'#43d6ae':'#ff6685'} fill={`url(#${positive?'up':'down'})`} strokeWidth={1.5}/></AreaChart></ResponsiveContainer></div>}
export function BigChart({data,color='#43d6ae',secondary}:{data:{time?:string;close?:number;v?:number}[],color?:string,secondary?:number[]}){const d=data.map((x,i)=>({i,label:x.time?.slice(5),v:x.close??x.v,second:secondary?.[i]}));return <div className="big-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={d}><XAxis dataKey="label" hide/><YAxis domain={['auto','auto']} hide/><Tooltip contentStyle={{background:'#0d1a20',border:'1px solid #26383f',borderRadius:8}}/><Line dataKey="v" stroke={color} dot={false} strokeWidth={2}/>{secondary&&<Line dataKey="second" stroke="#7394ff" dot={false}/>}</LineChart></ResponsiveContainer></div>}
export function ScoreRing({score,label}:{score:number,label:string}){return <div className="score-wrap"><div className="score-ring" style={{'--score':`${score*3.6}deg`} as React.CSSProperties}><div><strong>{score}</strong><small>/ 100</small></div></div><Badge tone="good">{label}</Badge></div>}
export function Skeleton(){return <div className="skeleton"><i/><i/><i/></div>}
export function ErrorState({retry}:{retry:()=>void}){return <div className="error-state"><b>Market data temporarily unavailable</b><span>Displaying no stale values. Check the backend connection.</span><button onClick={retry}>Retry connection</button></div>}
